image:
  repository: apache/gravitino
  tag: 0.9.1  # or use latest stable version
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
command:
  - gravitino
  - standalone