image:
  repository: apache/gravitino
  tag: 0.9.0-incubating  # ✅ safe fallback

service:
  type: ClusterIP
  port: 8090

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
command:
  - gravitino
  - standalone