version: "3.8"
services:

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio-data:/data  # Add this
    command: ["server", "/data", "--console-address", ":9001"]


  trino:
    image: trinodb/trino:436
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/etc/catalog:/etc/trino/catalog
      - ./trino/etc/core-site.xml:/etc/trino/core-site.xml
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    depends_on:
      - minio
    networks:
      - iceberg_net

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://minio:9000 admin password; do sleep 2; done;
      mc mb -p myminio/warehouse || true;
      mc policy set public myminio/warehouse;
      tail -f /dev/null
      "


volumes:
  minio-data:
networks:
  iceberg_net:
