apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: gravitino
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx512m"



curl -X POST http://localhost:8090/v1/catalogs -H "Content-Type: application/json" -d '{"name": "iceberg_catalog","type": "iceberg","comment": "Iceberg catalog on MinIO","properties": {"uri": "s3a://warehouse", "s3.endpoint": "http://minio:9000", "s3.access-key": "minioadmin", "s3.secret-key": "minioadmin", "warehouse": "s3a://warehouse"}}'