apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg-rest
  template:
    metadata:
      labels:
        app: iceberg-rest
    spec:
      containers:
        - name: iceberg-rest
          image: apache/iceberg-rest-fixture
          ports:
            - containerPort: 8181
          env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: password
            - name: CATALOG_AWS_ACCESS_KEY_ID
              value: admin
            - name: CATALOG_AWS_SECRET_ACCESS_KEY
              value: password
            - name: AWS_REGION
              value: us-east-1
            - name: CATALOG_WAREHOUSE
              value: s3://warehouse/path
            - name: CATALOG_IO__IMPL
              value: org.apache.iceberg.aws.s3.S3FileIO
            - name: CATALOG_S3_ENDPOINT
              value: http://192.168.1.114:9000
            - name: AWS_ENDPOINT
              value: http://192.168.1.114:9000
            - name: AWS_REGION
              value: us-east-1
            - name: CATALOG_S3_PATH_STYLE_ACCESS
              value: "true"
            - name: AWS_S3_SIGNATURE_VERSION
              value: AWS4-HMAC-SHA256
            - name: CATALOG_AWS_REGION
              value: us-east-1
            - name: CATALOG_S3_ACCESS_KEY_ID
              value: admin
            - name: CATALOG_S3_SECRET_ACCESS_KEY
              value: password


